[package]
name = "eggy1"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.57", features = ["derive"] }
egglog-experimental = { git = "https://github.com/egraphs-good/egglog-experimental.git" }